### ISSUE TITLE
Further output in API call

### ISSUE THREAD

**Issue by CFuerstenau** [bexis/Module_DataProfilingTools#20]
Would be nice if we had further information in the API:

- grassland: yes/no
- forest: yes/no
-REX1 : yes/no
- REX 2: yes/no
- LUX: yes/no
- FOX: yes/no

**Comment by EleonoraPetzold** [comment]
moved to https://github.com/bexis/Module_ResearchAreaManagement/issues/133

**Comment by EleonoraPetzold** [comment]
reopen, it is an issue for that repo

**Comment by EleonoraPetzold** [comment]
it works and there are no issues anymore
