### ISSUE TITLE
 Output whether new experiments are included

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_DataProfilingTools#3]
New Experiments show REX, FOX, etc if there are included.

Precondition: ref datasets in Bexis

**Comment by aostrow** [comment]
forest: https://www.bexis.uni-jena.de/ddm/data/Showdata/31307
grass:  https://www.bexis.uni-jena.de/ddm/data/Showdata/31040

**Comment by EleonoraPetzold** [comment]
It can be that there are 2 plot columns. Once EP and new Exp. If there are NAs in new Exp, both must be considered, otherwise only the NewExp.
Example: 31248
