### ISSUE TITLE
Testing PlotProfiling

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_DataProfilingTools#4]
http://be2020-dev.inf-bb.uni-jena.de:2010/dpt_be/PlotProfiling/index
In menu Tools/Plot Profiling Tool

- [x] File upload
- [x] direct textfield input
- [x] very long list of plots
- [x] different plots types (incl GP plot ids)
- [x] different list separator (allowed are comma, tab, line break)

**Comment by CFuerstenau** [comment]
- clear button für text field
- file header: checkbox davor
- separ

**Comment by EleonoraPetzold** [comment]
I enter some invaild input und test a file without file extension and it works. I have received many invaild plots in the process.
Are invaild plots ok as "error" or we need a seperate error message?
<img width="429" alt="image" src="https://user-images.githubusercontent.com/42029171/174240387-9b28e21d-cc71-4c6e-9cab-d73425f1ee84.png">

**Comment by aostrow** [comment]
What I do not really understand in the above picture
1st line: reported completely as error
2nd line: just the 2nd value is reported as error. The first value with the comma not.

Is it a separate issue? Do you currently allow just one white space? What happens if many commas are in the field?

**Comment by EleonoraPetzold** [comment]
Yes it is a separator issue. We allow comma, tab, line break as separator.

**Comment by EleonoraPetzold** [comment]
The question is whether we want an extra error message or if the display as not valid is enough.

**Comment by aostrow** [comment]
We would suggest also using the _semicolon_ and _white space_ as a separator. 

Would it be possible to 
- accept the separator independent of how often it is used (e.g., 1 or many commas between the PlotIDs) 
- or if it is mixed up (e.g., starting with a comma and later semicolon)?

**Comment by EleonoraPetzold** [comment]
**Testing new Exp**

- [ ] join Exp output

**Comment by aostrow** [comment]
Was it tested already? White space as a separator does not work. Also not in combination with a comma. 
Semicolon also not.

I think that the clear button is badly positioned directly below the box. I clicked it 2 times instead of count. Maybe we put the clear + upload option right to the box?

**Comment by EleonoraPetzold** [comment]
The separator issue is fixed! Please test it again.

**Comment by EleonoraPetzold** [comment]
> I think that the clear button is badly positioned directly below the box. I clicked it 2 times instead of count. Maybe we put the clear + upload option right to the box?

Or another kind of button (other style)? In my opinion, on the right site is not so useable, too.

**Comment by aostrow** [comment]
both buttons side by side below the box?

**Comment by EleonoraPetzold** [comment]
> both buttons side by side below the box?

yes :)

Do you test new exp plots, too?

**Comment by EleonoraPetzold** [comment]
> both buttons side by side below the box?

done

**Comment by EleonoraPetzold** [comment]
- [ ] Test massive number of plots

**Comment by EleonoraPetzold** [comment]
- [ ] ignore header if plot uploaded via file

**Comment by aostrow** [comment]
Something did not work correctly:

![image](https://user-images.githubusercontent.com/26480843/186120216-473bc32c-bb9c-4dc6-ad24-5b4b769fe44c.png)

I added:
- all joint exp. forest + grasland
- all EPs in EP-style (HEW8, ...)
- all EPs in GP-style (H302, ...)

**Comment by EleonoraPetzold** [comment]
> Something did not work correctly:
> 
> ![image](https://user-images.githubusercontent.com/26480843/186120216-473bc32c-bb9c-4dc6-ad24-5b4b769fe44c.png)
> 
> I added:
> 
> * all joint exp. forest + grasland
> * all EPs in EP-style (HEW8, ...)
> * all EPs in GP-style (H302, ...)

Please provide your input via mail

**Comment by aostrow** [comment]
I had some missing EPs in EP-style in my testfile. I corrected it. The result is still not correct. I will send the file.

**Comment by EleonoraPetzold** [comment]
> I had some missing EPs in EP-style in my testfile. I corrected it. The result is still not correct. I will send the file.

fixes with #12

**Comment by EleonoraPetzold** [comment]
all things are fixed or in sep issues
